- name: install and run the package
  hosts: web
  become: yes #its will get root access
  tasks:
  - name: install nginx package
    ansible.bulitin.package:
      name: nginx
      state: present
  - name: run nginx
    ansible.builtin.service:
      name: nginx
      state: present