- name: install and run the package
  hosts: web
  tasks:
  - name: install nginx package
    ansible.bulitin.package:
      name: nginx
      state: present
  - name: run nginx
    ansible.builtin.package:
      name: nginx
      state: present