- name: varibles from play
  hosts: localhost
  vars:
    subject: "devops"
    teacher: "sivakumar"
    period: "110hrs"
  tasks:
  - name: varibles from task
    vars:
      subject: "devops with aws"
      teacher: "sivakumar"
      period: "110hrs" 
    ansible.builtin.debug:
      msg: "this is {{subject}} trained by {{teacher}} and duration is {{period}}