- name: varibles from play
  hosts: localhost
  vars:
    COURSE: "devops"
    TRAINER: "sivakumar"
    DURATION: "110hrs"
  tasks:
  - name: varibles from task
    vars:
      COURSE: "devops with aws"
      TRAINER: "sivakumar"
      DURATION: "110hrs" 
    ansible.builtin.debug:
      msg: "this is {{COURSE}} trained by {{TRAINER}} and duration is {{DURATION}}