- name: variable
  hosts: localhost
  vars_files:
  - variablefile.yaml
  tasks:
  - name: variable file
    ansible.builtin.debug:
      msg: "this is {{COURSE}}, trained by {{TRAINER}} and duration is {{DURATION}}"