- name: datatypes
  hosts: localhost
  vars:
    NAME: brahmam #ist key value
    SKILLS: # skilss us a list type
    - devops
    - aws
    - ansible
    - kubarnates
    EXPERIENCE: #its map
      devopsaws: 3
      aws1: 3
      docker: 1
  tasks:
  - name: check key value
    ansible.builtin.debug:
      msg: "hi i am {{NAME}}"
  - name: check list
    ansible.builtin.debug:
      msg: "my skillset {{SKILLS}}"
  - name: check map
    ansible.builtin.debug:
      msg: "my experince {{EXPERIENCE}}"