- name: conditions
  hosts: localhost
  tasks:
  - name: check conditions
    ansible.builtin.command: Id roboshop
    register: user # id of status stored in user. it is a varible
    ignore_errors: true # ansible will not exist even if it got error

  - name: print user
    ansible.builtin.debug:
      msg: "usr is {{user}}"
  
  - name: print exit status
    ansible.builtin.debug:
      msg: "user status {{user.rc}}" # rc means return code or exist status
