- name: installing packages
  hosts: localhost
  become: yes
  tasks:
  - name: installing pacakges
    ansible.builtin.package:
      name: "{{item.name}}"
      state: "{{item.state}}"
    loop:
    - {name: 'mysql',state:'absent'}
    - {name: 'git',state:'absent'}
    - {name: 'postfix',state:'present'}
      